services:
  game:
    build: game
    env_file:
      - .env
    ports:
      - ${SPIRE_GAME_LISTEN_PORT}:${SPIRE_GAME_LISTEN_PORT}
      - ${SPIRE_ADMIN_LISTEN_PORT}:${SPIRE_ADMIN_LISTEN_PORT}
    secrets:
      - game-cert.pem
      - game-key.pem
      - db-password.txt
      - auth-key.txt
    depends_on:
      db:
        condition: service_healthy
  
  lobby:
    build: lobby
    env_file:
      - .env
    ports:
      - ${SPIRE_LOBBY_PORT}:${SPIRE_LOBBY_PORT}
    secrets:
      - db-password.txt
      - lobby-cert.pem
      - lobby-key.pem
      - auth-key.txt

  db:
    build: db
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_HOST: ${SPIRE_DB_HOST}
      MYSQL_PORT: ${SPIRE_DB_PORT}
      MYSQL_DATABASE: ${SPIRE_DB_NAME}
      MYSQL_USER: ${SPIRE_DB_USER}
      MYSQL_PASSWORD_FILE: ${SPIRE_DB_PASSWORD_FILE}
    ports:
      - ${SPIRE_DB_PORT}:${SPIRE_DB_PORT}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    secrets:
      - db-password.txt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
  db-data:

secrets:
  game-cert.pem:
    file: secrets/game-cert.pem
  game-key.pem:
    file: secrets/game-key.pem
  db-password.txt:
    file: secrets/db-password.txt
  auth-key.txt:
    file: secrets/auth-key.txt
  lobby-cert.pem:
    file: secrets/lobby-cert.pem
  lobby-key.pem:
    file: secrets/lobby-key.pem