services:
  game-server:
    build: game-server
    env_file:
      - .env
    ports:
      - ${SPIRE_GAME_SERVER_PORT}:${SPIRE_GAME_SERVER_PORT}
      - ${SPIRE_GAME_SERVER_CONTROL_PORT}:${SPIRE_GAME_SERVER_CONTROL_PORT}
    secrets:
      - game-server-cert.pem
      - game-server-key.pem
      - db-password.key
      - token.key
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "/app/build/release/ping", "localhost", "${SPIRE_GAME_LISTEN_PORT}"]
    #   interval: 1m
    #   start_period: 1m
  
  lobby-server:
    build: lobby-server
    env_file:
      - .env
    environment:
      - NODE_ID=101
    ports:
      - ${SPIRE_LOBBY_SERVER_PORT}:${SPIRE_LOBBY_SERVER_PORT}
    secrets:
      - lobby-server-cert.pem
      - lobby-server-key.pem
      - token.key
      - db-password.key
    # depends_on:
    #   db:
    #     condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:${SPIRE_LOBBY_SERVER_PORT}/ping"]
      interval: 1m
      start_period: 30s

  db:
    build: db
    env_file:
      - .env
    environment:
      - GEL_SERVER_USER=${SPIRE_DB_USER}
      - GEL_SERVER_PASSWORD_FILE=${SPIRE_DB_PASSWORD_FILE}
      - GEL_SERVER_TLS_CERT_MODE=generate_self_signed
      # - GEL_SERVER_TLS_CERT_FILE=${SPIRE_DB_TLS_CERT_FILE}
      # - GEL_SERVER_TLS_KEY_FILE=${SPIRE_DB_TLS_KEY_FILE}
      - GEL_SERVER_INSTANCE_NAME=spire-db
      - GEL_SERVER_ADMIN_UI=enabled
    ports:
      - ${SPIRE_DB_PORT}:${SPIRE_DB_PORT}
    volumes:
      - db-data:/var/lib/gel/data
    secrets:
      - db-password.key
      - db-cert.pem
      - db-key.pem
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${SPIRE_DB_USER}", "-d", "${SPIRE_DB_NAME}"]

volumes:
  db-data:

secrets:
  token.key:
    file: secrets/token.key
  game-server-cert.pem:
    file: secrets/game-server-cert.pem
  game-server-key.pem:
    file: secrets/game-server-key.pem
  db-cert.pem:
    file: secrets/db-cert.pem
  db-key.pem:
    file: secrets/db-key.pem
  db-password.key:
    file: secrets/db-password.key
  lobby-server-cert.pem:
    file: secrets/lobby-server-cert.pem
  lobby-server-key.pem:
    file: secrets/lobby-server-key.pem