services:
  game-server:
    env_file:
      - local.env
    environment:
      - NODE_ID=${SPIRE_GAME_SERVER_NODE_ID}
    networks:
      - local-network
    hostname: ${SPIRE_GAME_SERVER_HOST}
  
  lobby-server:
    env_file:
      - local.env
    environment:
      - NODE_ID=${SPIRE_LOBBY_SERVER_NODE_ID}
    networks:
      - local-network
    hostname: ${SPIRE_LOBBY_SERVER_HOST}

  db:
    env_file:
      - local.env
    networks:
      - local-network
    hostname: ${SPIRE_DB_HOST}

  db-admin:
    env_file:
      - local.env
    networks:
      - local-network
    hostname: ${SPIRE_DB_ADMIN_HOST}

networks:
  local-network:
    driver: bridge
