services:
  logic-server:
    build: logic-server
    env_file:
      - .env
    ports:
      - ${SPIRE_LOGIC_LISTEN_PORT}:${SPIRE_LOGIC_LISTEN_PORT}
      - ${SPIRE_ADMIN_LISTEN_PORT}:${SPIRE_ADMIN_LISTEN_PORT}
    secrets:
      - logic-cert.pem
      - logic-key.pem
      - database-password.txt
      - auth-key.txt
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "/app/build/release/ping", "localhost", "${SPIRE_LOGIC_LISTEN_PORT}"]
    #   interval: 1m
    #   start_period: 1m
  
  lobby-server:
    build: lobby-server
    env_file:
      - .env
    ports:
      - ${SPIRE_LOBBY_PORT}:${SPIRE_LOBBY_PORT}
    secrets:
      - database-password.txt
      - lobby-cert.pem
      - lobby-key.pem
      - auth-key.txt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:${SPIRE_LOBBY_PORT}/ping"]
      interval: 1m
      start_period: 30s

  database:
    build: database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SPIRE_DATABASE_USER}
      POSTGRES_PASSWORD_FILE: ${SPIRE_DATABASE_PASSWORD_FILE}
      POSTGRES_DB: ${SPIRE_DATABASE_NAME}
    ports:
      - ${SPIRE_DATABASE_PORT}:${SPIRE_DATABASE_PORT}
    secrets:
      - database-password.txt
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SPIRE_DATABASE_USER}", "-d", "${SPIRE_DATABASE_NAME}"]

volumes:
  database-data:

secrets:
  logic-cert.pem:
    file: secrets/logic-cert.pem
  logic-key.pem:
    file: secrets/logic-key.pem
  database-password.txt:
    file: secrets/database-password.txt
  auth-key.txt:
    file: secrets/auth-key.txt
  lobby-cert.pem:
    file: secrets/lobby-cert.pem
  lobby-key.pem:
    file: secrets/lobby-key.pem